[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "3000"
NODE_ENV = "production"
BACKEND_URL = "https://asmlmbackend-production.up.railway.app"
VITE_API_BASE_URL = ""

